all: isuumo

isuumo:
	deno bundle app.ts > isuumo

run:
	deno run --allow-net --allow-run --allow-read --allow-env ./isuumo

rundev:
	deno run --allow-net --allow-run --allow-read --allow-env ./app.ts
