- name: Initialize isucon10
  become: yes
  become_user: isucon
  command: curl -X POST http://localhost/initialize

- name : Snapshot isucon10
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/isuumo/initial-data/
  environment:
    PATH: "/home/isucon/local/go/bin:/home/isucon/local/node/bin:/home/isucon/local/ruby/bin:/home/isucon/local/python/bin:/home/isucon/local/perl/bin:/home/isucon/local/php/bin:/home/isucon/.cargo/bin:/home/isucon/.deno/bin:/home/isucon/bin:/home/isucon/.local/bin:/usr/bin:/sbin:/bin"
  shell: |
    go build -o ./make_verification_data/main ./make_verification_data/*.go && ./make_verification_data/main -fixture-dir ../webapp/fixture -dest-dir ./result/verification_data -target-url http://localhost:1323


- name: Build benchmarker
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/isuumo/bench/
  environment:
    PATH: "/home/isucon/local/go/bin:/home/isucon/local/node/bin:/home/isucon/local/ruby/bin:/home/isucon/local/python/bin:/home/isucon/local/perl/bin:/home/isucon/local/php/bin:/home/isucon/.cargo/bin:/home/isucon/.deno/bin:/home/isucon/bin:/home/isucon/.local/bin:/usr/bin:/sbin:/bin"
  shell: |
    make

- name: Disable Unused Services
  become: yes
  become_user: root
  shell: |
    systemctl disable isucon-go && \
    systemctl disable mysql && \
    systemctl disable nginx

- name: Check isucon10-portal
  become: no
  stat:
    path: "/home/isucon/portal"
  register: chk_file

- name: Delete isucon10-portal if exists
  become: yes
  become_user: root
  file:
    path: /home/isucon/poratl
    state: absent
  when: chk_file.stat.exists

- name: Clone isucon10-portal
  become: no
  git:
    repo: git@github.com:isucon/isucon10-portal.git
    version: master
    dest: /tmp/isucon10-portal
    accept_hostkey: yes

- name: Chgroup sisucon10-portal repo
  become: yes
  become_user: root
  file:
    path: /tmp/isucon10-portal
    state: directory
    owner: isucon
    group: isucon
    recurse: yes

- name: Deploy isucon10-portal
  become: yes
  become_user: isucon
  command: mv /tmp/isucon10-portal /home/isucon/portal

- name: Make Supervisor
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/portal/supervisor
  environment:
    PATH: "/home/isucon/local/go/bin:/home/isucon/local/node/bin:/home/isucon/local/ruby/bin:/home/isucon/local/python/bin:/home/isucon/local/perl/bin:/home/isucon/local/php/bin:/home/isucon/.cargo/bin:/home/isucon/.deno/bin:/home/isucon/bin:/home/isucon/.local/bin:/usr/bin:/sbin:/bin"
  shell: |
    cargo build --release

- name: Copy env.sh for supervisor
  become: yes
  become_user: isucon
  copy:
    src: "env.sh"
    dest: /home/isucon/portal

- name: Copy service file
  copy:
    src: "{{ item }}"
    dest: "/etc/systemd/system"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items:
    - isucon-supervisor.service
- name: Start "supevisor"
  systemd:
    daemon_reload: "yes"
    name: "isucon-supervisor"
    state: "restarted"
    enabled: "yes"
