- name: Initialize isucon10
  become: yes
  become_user: isucon
  command: curl -X POST http://localhost/initialize

- name : Snapshot isucon10
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/isucon10-qualify/initial-data/
  environment:
    PATH: "/home/isucon/bin:/home/isucon/.local/bin:/usr/local/node/bin:/usr/local/python/bin:/usr/local/go/bin:/home/isucon/go/bin:/usr/local/bin:/usr/bin:/bin"
  shell: |
    go build -o ./make_verification_data/main ./make_verification_data/*.go && ./make_verification_data/main -fixture-dir ../webapp/fixture -dest-dir ./result/verification_data -target-url http://localhost:1323


- name: Build benchmarker
  become: yes
  become_user: isucon
  args:
    chdir: /home/isucon/isucon10-qualify/bench/
  environment:
    PATH: "/home/isucon/bin:/home/isucon/.local/bin:/usr/local/node/bin:/usr/local/python/bin:/usr/local/go/bin:/home/isucon/go/bin:/usr/local/bin:/usr/bin:/bin"
  shell: |
    make

- name: Disable Unused Services
  become: yes
  become_user: root
  shell: |
    systemctl disable isucon-go && \
    systemctl disable mysql && \
    systemctl disable nginx

- name: Download netdata install script
  become: yes
  get_url:
    url: https://my-netdata.io/kickstart.sh
    dest: /tmp/kickstart.sh
    mode: '0775'

- name: Install netdata
  become: yes
  shell: /tmp/kickstart.sh --dont-wait
